name: Continues Integration

on:
  workflow_dispatch:
  pull_request:
  push:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet:
          [{ ch: "3.1", ver: "netcoreapp31" }, { ch: "6.0", ver: "net60" }]

    steps:
      - name: Initialize Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Initialize SurrealDB
        run: |
          mkdir -p ~/.local/bin
          export INSTALL_DIR=~/.local/bin
          curl -sSf https://install.surrealdb.com | sh
          export PATH="$HOME/.local/bin/:$PATH"

      - name: Initialize .NET SDK
        run: |
          curl https://dot.net/v1/dotnet-install.sh -o ~/dotnet-install.sh
          chmod +x ~/dotnet-install.sh
          ~/dotnet-install.sh -c ${{ matrix.dotnet.ch }}
          dotnet --info

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore -f:${{ matrix.dotnet.ver }}

      - name: Execute Unit-Tests
        run: |
          dotnet test --no-build -f:${{ matrix.dotnet.ver }} --verbosity normal --logger "trx;LogFileName=$(pwd)/test-results.trx" --collect:"XPlat Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura\" /p:CoverletOutput="$(pwd)/" /p:UseSourceLink=true

      - name: Test Report
        if: success() || failure()
        uses: phoenix-actions/test-reporting@v8
        with:
          name: unittest-results
          path: test-results.trx
          reporter: dotnet-trx
          fail-on-error: false

      - name: Test Coverage
        if: github.ref == 'ref/heads/master'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.cobertura.xml
          flags: unittests
          name: Surreal.Net
          fail_ci_if_error: false
          verbose: true
