name: Documentation

on:
  push:
    branches: [master]
    paths-ignore:
      - ".github/"
      - "tests/"
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - uses: actions/checkout@v2

      - name: Initialize Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Initialize .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Initialize MkDocs
        run: pip install mkdocs-material mkdocs-section-index

      - name: Initialize .NET tools
        run: |
          dotnet tool install --global SourceLinkExtract
          dotnet tool install --global SourceSymbolMapper
          dotnet tool install --global XmlDocMdSymbols

      - name: Build Release
        run: dotnet build -f:net60 -c:Release -o:publish

      - name: Generate Documentation Source
        run: ./.github/generate_docs.sh

      - name: Generate MKDocs 'nav' Entry
        run: |
          chmod +x ./.github/generate_docs_nav.py
          ./.github/generate_docs_nav.py >> mkdocs.yml

      - name: Deploy Documentation
        run: mkdocs gh-deploy --force
