name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag
        required: true
      message:
        type: string
        description: Message
        required: true
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true
defaults:
  run:
    shell: bash

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Merge master -> release-stable
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: release-stable
          github_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          ref: release-stable

      - name: Patch version
        id: patch-version
        run: |
          ../patch_version.sh ${{ github.event.inputs.tag }}

      - name: Commit version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: "--no-verify --signoff"
          file_pattern: "**.props *.md"

      - name: Merge release-stable -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: release-stable
          target_branch: master
          github_token: ${{ github.token }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }} - ${{ github.event.inputs.message }}
          generateReleaseNotes: true
